server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: ms-usermanagement
        uri: http://localhost:8081/
        predicates:
        - Path=/api/user/**
      - id: ms-taskmanagement
        uri: http://localhost:8082/
        predicates:
        - Path=/api/task/**